apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: new-template-test
  title: Test de new template
  description: Lets test
  annotations:
    selfservice.devportal.yape.tech/visible: "true"
    selfservice.devportal.yape.tech/icon: icCode
    selfservice.devportal.yape.tech/color: violet
spec:
  owner: Product Platform
  type: service
  parameters:
    - title: Nova pagina
      required:
        - name
      properties:
        name:
          title: Nome
          type: string
